### ISSUE TITLE
Configurar plugin do dependabot no build.yml

### ISSUE THREAD

**Issue by manoelcampos** [iftopalmas/sistemas-viagens#45]
O workflow do GitHub Action .github/build.yml tinha as seguintes linhas no final:

```yml
     # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
     - name: Update dependency graph
       uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
```

Isto habilita o plugin do dependabot para detectar falhas de segurança nas libs do projeto.
No entanto, como não temos um projeto na raiz do repositório, isso não funciona.
Seria preciso criar um workflow para cada projeto. 

Veja a página da [action](https://github.com/marketplace/actions/maven-dependency-tree-dependency-submission) se precisar de detalhes. Possivelmente, criando múltiplos workflows para cada projeto, não precisa configurar nada na action do dependabot.
